export const HOMEPAGE_LINK = process.env.REACT_HOMPAGE_URL || '/'
export const APP_LINK = process.env.REACT_APP_URL || 'http://localhost:3001'
export const BLOG_LINK = 'https://medium.com/deltafi'
export const TWITTER_LINK = 'https://twitter.com/deltafi_ai'
export const DISCORD_LINK = 'https://discord.com/invite/6maaM2cYqr'
export const GITHUB_LINK = 'https://github.com'
export const PINTEREST_LINK = "https://pinterest.com"
export const YOUTUBE_LINK = "https://youtube.com"
export const CAREERS_LINK = "/career"
export const PRIVACY_LINK = "/privacy"